version = 0.1

[default.deploy.parameters]
stack_name = "JordanUserServiceStack"
resolve_s3 = true
s3_bucket = "jordan-user-service-s3"
s3_prefix = "JordanUserServiceStack"
region = "us-east-2"
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
image_repositories = []
confirm_changeset = true
parameter_overrides = "StageName=\"Dev\""

[default.deploy.env_vars]
AWS_SAM_CLI_READLINE_ENABLED = true
_JAVA_OPTIONS = "-Djava.library.path=./lib -Djava.awt.headless=true"

